print:
  target:
    device:
      integration: niimbot
  fields:
    payload:
      required: true
      example: |
        - type: text
          value: Hello World!
          x: 5
          y: 5
          size: 40
      default:
        - type: text
          value: Hello World!
          x: 5
          y: 5
          size: 40
      selector:
        object:
    rotate:
      required: false
      example: '0'
      selector:
        number:
          min: 0
          max: 270
          step: 90
    width:
      required: false
      example: 400
      default: 400
      selector:
        number:
          min: 10
          max: 1600
          step: 1
    height:
      required: false
      example: 240
      default: 240
      selector:
        number:
          min: 10
          max: 1600
          step: 1
    density:
      required: false
      default: 3
      selector:
        number:
          min: 1
          max: 5
          step: 1
    wait_between_print_lines:
      required: false
      default: 0.05
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    print_line_batch_size:
      required: false
      default: 1
      selector:
        number:
          min: 1
          max: 512
          step: 1
    preview:
      required: false
      example: 'false'
      selector:
        boolean:
    dither:
      required: false
      example: false
      selector:
        boolean:
